### ISSUE TITLE
Singular/Plural resource question

### ISSUE THREAD

**Issue by kenshinji** [Wiredcraft/test-backend#12]
According to [this post](https://stackoverflow.com/questions/6845772/rest-uri-convention-singular-or-plural-name-of-resource-while-creating-it) from StackOverflow, I think it is should be okay to use plural form to represent resource when we refer to the REST URI. So I need you guys' confirmation about that. :)

**Comment by makara** [comment]
Yeah it's OK, but Loopback also has its conventions. Please figure out.
