### ISSUE TITLE
Clarification on requirements 

### ISSUE THREAD

**Issue by jakangah** [Wiredcraft/test-backend#21]
There are a couple of things I would need clarification on.

1. Can I get more clarification on the filter feature? Does it mean after getting some records from the data store, I filter those records passed on multiple fields or just one field?
2. Do I need to do pure CRUD with the users (soft or hard delete)?
3. Are all fields in the user model required? And if not can I be told which ones are 
4. And I’m I permitted to add extra fields to handle authentication in the user model? If not can I create extra models to support this? If not I will simulate the process by return a valid token always whether the credentials are correct or not

**Comment by makara** [comment]
Hey @jakangah, generally speaking, please consider the quiz less of a complete requirement document, and proceed with some reasonable assumption.

> Can I get more clarification on the filter feature? Does it mean after getting some records from the data store, I filter those records passed on multiple fields or just one field?

That would mean after getting ALL the records from the DB, you filter the records with SOME fields. But, you could use 1 or a few fields to demostrate how you do it.

> Do I need to do pure CRUD with the users (soft or hard delete)?

Please proceed with your choice. It'd be cool if you document about the ideas.

> Are all fields in the user model required? And if not can I be told which ones are

Up to you

> And I’m I permitted to add extra fields to handle authentication in the user model? If not can I create extra models to support this? If not I will simulate the process by return a valid token always whether the credentials are correct or not

Up to you but please document about your model design, for example the attributes and the purpose of them etc.

**Comment by jakangah** [comment]
Thanks , for the clarification
