### ISSUE TITLE
Should I build an oauth server or just make a user login api?

### ISSUE THREAD

**Issue by lymanlai** [Wiredcraft/test-backend#38]
Hi there
   One question: 
   "Provide a complete user auth (authentication/authorization/etc.) strategy, such as OAuth".
    Does this mean that we create a login method for user that they can login by use like wechat/weibo? 
    Or it means we create a OAuth login server provide the service like wechat/webo login?

Thanks.

**Comment by xavierchow** [comment]
The former, building an OAuth provider would be too much for a test.
@lymanlai

**Comment by lymanlai** [comment]
oh, I just think about create a OAuth service platform ;)
