### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by Tong-Huang** [Wiredcraft/test-backend#39]
## Required Fields
 
I think the fields `id` and `name` should be required and `dob`, `address `,  `description ` is optional. The `createdAt` field will have a default value when the user is created.

| Field       | Type    | Required  |  Nullable | Default Value |Remark |
| :----       | :----   | :----:    | :----:    | :----:        | :---- |
| id          | string  | Y         | N         |  UUID         |User ID |
| name        | string  | Y         | N         |  -            |User name |
| dob         | date    | N         | Y         |  -            |Date of birth |
| address     | string  | N         | Y         |  -            |User address |
| description | string  | N         | Y         |  -            |User description |
| createdAt   | date    | N         | N         |  Date.now()   |User created date |

And I will add a **unique** index for the `name` field.

## The `password` field

I find that the `password` field is omitted in the user model present in the README file.

I want to add a `UserCredentials` model to persist the user's password.

Each user only has one `UserCredentials`. The relation is one to one.

It will be used to perform JWT auth and some action like user login.

**Comment by xavierchow** [comment]
Yes, you can define the fields according to your understanding.
> And I will add a unique index for the name field.

Here do you mean you want to add a unique constraint on `name`? Sure you can add it if it makes sense to you.

> I find that the password field is omitted in the user model present in the README file.

As not everybody will work on the `authentication` feature, it's omitted but it's ok to go with your model design.

**Comment by Tong-Huang** [comment]
Gotcha.
