### ISSUE TITLE
Q&A about the requirement

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/test-backend#4]
@makara 
Hi, It seems the requirement of this quiz is just making a restful API for `user` resource, it doesn't relate to any login or authentication you mentioned in mail. Am I missing sth?

**Comment by makara** [comment]
Well the readme here is for a previous test.

**Comment by sylvainv** [comment]
Hi, i am curious about authentication too. Am I missing something as well or is it not required ?

**Comment by sylvainv** [comment]
Another question is that I have to use Loopback.io for this test. After starting to program a little bit, it seems a bit weird to me since the goal is also to test the code and unit testing. But if I use loopback.io I won't have to write much code, mostly configuration and probably not much unit testing either, since it's all the work is done by Loopback. I am now a bit confused by the purpose of the test.

**Comment by ChopperLee2011** [comment]
@sylvainv the authentication part is not the 'Requirements' in this task, but it should be common sense to have this feature with user's API, and it will make ur work more impressive than others if u have a stable well-designed solution, if u know what I mean. 
For the other question, our team use mocha && chai for making unit test on loopback, it is nothing more than testing express app, my point is that u still need test code for confirming all ur restful api works as expected, even mostly logic is generated by loopback framework.
At last, I know this task maybe a little simple, so the bonus is how much u can handle a new backend framework in the limit time, and how many ideas u can bring to for this project, such as authentication solution, logging solution, or devops solution. Please do not limit ur thought by the requirements, it is not a standard work, it is a open-mind task for hiring people.

**Comment by sylvainv** [comment]
ok thanks.

**Comment by xavierchow** [comment]
Closing, feel free to reopen it if there's any questions.
