### ISSUE TITLE
Password field on User model

### ISSUE THREAD

**Issue by SEdilson** [Wiredcraft/test-backend#44]
Hello guys, so i'm not currently applying for the backend position at Wiredcraft but i'd like to submit the challenge for a review, is that possible?

My second doubt is if i could insert the password field at the user model or this model has to follow the example given at the README of the repo and then i had to create another model only to make the authentication?

**Comment by xavierchow** [comment]
@SEdilson hello, thank for your interest in this repo, I'm afraid we are not able to review the PR if you didn't apply for the backend position from https://wiredcraft.com/jobs/backend-developer/.

closing the ticket for now, 
feel free to leave a comment here if you have further questions or just try to apply for the backend position  :)
