### ISSUE TITLE
A few questions about the requirements

### ISSUE THREAD

**Issue by bsdelf** [Wiredcraft/test-backend#46]
The first one is about user model, does the description in README suggest that following attributes should be string?

- id
- dob
- createdAt

> ```
> {
>   "id": "xxx",                  // user ID 
>   "name": "test",               // user name
>   "dob": "",                    // date of birth
>   "address": "",                // user address
>   "description": "",            // user description
>   "createdAt": ""               // user created date
> }
> ```

My thoughts:

- id: in practice, a lot of web APIs just use incremental primary key as ID, it is quite convenient and efficient, unless there are special concerns like security risk, key space limitation. There is also a discussion about this topic on [stackoverflow](https://stackoverflow.com/questions/396164/exposing-database-ids-security-risk).
- date: stick to Unix timestamp in protocol and let client side determine how to render date (timezone, locale, format style) can provide more flexibility.

The second question is about the uniqueness of user name,

> Related to the requirement above, suppose the address of user now includes a geographic coordinate(i.e., latitude and longitude), can you build an API that,
>
> - given a user name
> - return the nearby friends

According to this requirement, it would be necessary to add a unique constraint to user name, otherwise the result of this API might be ambiguous. Also, the style of this API (using name instead of ID as search key) would affect the user <del>C</del>URD API design: `/users/:name` looks better than `/users/:id`, after all we need `/users/:name/friends`. Moreover, since the user name will be used as key, it might need more strict validation rules like only lowercases are allowed to avoid frauds ("Alice" vs "alice").

I'm not very sure whether my deduction fits the requirements or not.

**Comment by xavierchow** [comment]
@bsdelf 

1. You can define the type of the attributes if you see it's a fit with a reasonable explanation.

2. There is an ambiguousness in the requirement, I think you can forget about the name but use `id` to identify the user and get the nearby friends in this task.

**Comment by bsdelf** [comment]
Thanks for this information.
